spring:
  cloud:
    stream:
      bindings:
        fusFunction:
          destination: topic-enrich
          group: fus-group-id
        roFunction:
          destination: topic-deliver
          group: ro-group-id
        dahFunction:
          group: dah-group-id
      binders:
        kafka:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:9092

